"""
Minimal NumPy inference engine for exported SB3 PPO actor policies.

Expected weights format:
- NPZ generated by src/export_policy_numpy.py
- Flat op list with linear layers and activation names
"""

from __future__ import annotations

from pathlib import Path
from typing import List, Sequence, Tuple

import numpy as np


class PpoNumpyPolicy:
    """Lightweight deterministic actor inference using only NumPy."""

    def __init__(self, weights_path: str | Path):
        self.weights_path = Path(weights_path)
        if not self.weights_path.exists():
            raise FileNotFoundError(f"Policy weights not found: {self.weights_path}")

        data = np.load(self.weights_path, allow_pickle=False)

        self.obs_dim = int(data["obs_dim"][0])
        self.action_dim = int(data["action_dim"][0])
        self.input_dim = self.obs_dim  # Compatibility with existing real runner code.

        self.op_types: List[str] = [str(x) for x in data["op_types"].tolist()]
        self.op_names: List[str] = [str(x) for x in data["op_names"].tolist()]

        linear_count = int(data["linear_count"][0])
        self.linear_layers: List[Tuple[np.ndarray, np.ndarray]] = []
        for idx in range(linear_count):
            w_key = f"linear_{idx}_weight"
            b_key = f"linear_{idx}_bias"
            if w_key not in data or b_key not in data:
                raise KeyError(f"Missing linear tensors in NPZ: {w_key} / {b_key}")
            w = np.asarray(data[w_key], dtype=np.float32)
            b = np.asarray(data[b_key], dtype=np.float32)
            if w.ndim != 2 or b.ndim != 1 or w.shape[0] != b.shape[0]:
                raise ValueError(
                    f"Invalid linear tensor shapes for layer {idx}: weight={w.shape}, bias={b.shape}"
                )
            self.linear_layers.append((w, b))

        expected_linear_ops = sum(1 for op in self.op_types if op == "linear")
        if expected_linear_ops != len(self.linear_layers):
            raise ValueError(
                "Mismatch between op graph and linear tensors: "
                f"ops={expected_linear_ops}, tensors={len(self.linear_layers)}"
            )

    def predict(self, obs: np.ndarray) -> np.ndarray:
        """Run deterministic actor forward pass.

        Args:
            obs: shape (obs_dim,) or (batch, obs_dim)

        Returns:
            Action array of shape (action_dim,) or (batch, action_dim).
        """
        x = np.asarray(obs, dtype=np.float32)
        single = False

        if x.ndim == 1:
            x = x.reshape(1, -1)
            single = True
        elif x.ndim != 2:
            raise ValueError(f"obs must be 1D or 2D, got shape {x.shape}")

        if x.shape[1] != self.obs_dim:
            raise ValueError(f"obs dim mismatch: expected {self.obs_dim}, got {x.shape[1]}")

        linear_idx = 0
        for op in self.op_types:
            if op == "linear":
                w, b = self.linear_layers[linear_idx]
                x = x @ w.T + b
                linear_idx += 1
            else:
                x = self._apply_activation(op, x)

        x = x.astype(np.float32, copy=False)
        return x[0] if single else x

    @staticmethod
    def _apply_activation(name: str, x: np.ndarray) -> np.ndarray:
        if name == "tanh":
            return np.tanh(x)
        if name == "relu":
            return np.maximum(x, 0.0)
        if name == "elu":
            return np.where(x > 0.0, x, np.exp(x) - 1.0)
        if name == "leaky_relu":
            return np.where(x > 0.0, x, 0.01 * x)
        if name == "sigmoid":
            return 1.0 / (1.0 + np.exp(-x))
        if name == "identity":
            return x
        raise ValueError(f"Unsupported activation in exported graph: {name}")


__all__: Sequence[str] = ["PpoNumpyPolicy"]
